# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 154ced3237615c8df99abcc768ad8075c9bfe37453e44d067510f871e2a38e6c8d188b7ff59014fc80ee041230725fad51639d245faa928ef476de3abf2f4840

test:
  secret_key_base: 96f0effd874703b4bdd293aac4529c019f3d626261c775fa1873a51a31f9759d4c67305ec27e2009edf8098524a4c513df9686f40e8bf795a5d3fe6782a32fcf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
